---
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-release.yml@1199d20d99f1557a6e4984a94eb6c47a36f365e8 # main
    name: GitHub Release
